server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/identity_service
    username: root
    password: root
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "22d14ba61b98c7499371c1838b0c896e5afa40b676ec5e8e4dad58938ed06283"
  expirationTime: 20 # seconds
  refreshableTime: 120 # seconds
